### ISSUE TITLE
Grammar fails to highlight large, legal XML files

### ISSUE THREAD

**Issue by alexchandel** [atom/language-xml#76]
### Description

Large, legal XML files fail to highlight with this grammar. In particular a 3.9 MB file, with roughly 30,000 nodes, doesn't highlight at all.

Moreover, even if I delete the entire contents of the file except for the outermost tag pairs, while keeping the tab open, the grammar never highlights it. Switching the tab to another grammar and then switching it back to XML doesn't fix it either. The tab has to be closed and reopened.

**Comment by alexchandel** [comment]
The files notably contain CDATA sections with multiple lines. I've seen this cause problems before elsewhere. Are these parsed correctly?

**Comment by huckl3b3rry87** [comment]
I am also having issues where the syntax is not highlighted for XML files, but it is for all files and I have never used it before. Is there some box that I am probably forgetting to check in settings?

**Comment by 50Wliu** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by huckl3b3rry87** [comment]
never hear of that before...

So, does a file named.."file" work the same as "file.xml"

**Comment by 50Wliu** [comment]
@huckl3b3rry87 My comment was directed towards @alexchandel, not you.  Your issue can be solved by following the instructions at https://discuss.atom.io/t/how-do-i-make-atom-recognize-a-file-with-extension-x-as-language-y/26539.

**Comment by huckl3b3rry87** [comment]
@50Wliu thank you!
